# Generated by Xplorer, do not modify.
# This Makefile builds _single_build Debug

%:: RCS/%,v
%:: RCS/%
%:: s.%
%:: SCCS/s.%
.SUFFIXES:
.SUFFIXES: .a .o .c .cc .C .cpp .s .S .h


# There should not be an 'sh.exe' in path
export SHELL = cmd


# There should never be any unknown unix-like tools on the path
# In particular there should not be an 'sh.exe' in the system32 directory
export PATH = D:\Users\lgruc\xtensa\XtDevTools\install\tools\RI-2021.8-win32\XtensaTools\bin\;D:\Users\lgruc\xtensa\XtDevTools\install\tools\RI-2021.8-win32\XtensaTools\lib\iss\;C:\WINDOWS\system32

all:
	cmd /c "cd /D ""D:\\Users\\lgruc\\xtensa\\Xplorer-9.0.18-workspaces\\dsp_audio_algorithms_hifi4\\bin\\nxp_rt600_RI2021_8_newlib\\Debug"" && $(MAKE) all  "

clean:
	cmd /c "cd /D ""D:\\Users\\lgruc\\xtensa\\Xplorer-9.0.18-workspaces\\dsp_audio_algorithms_hifi4\\bin\\nxp_rt600_RI2021_8_newlib\\Debug"" && $(MAKE) clean  "
